import { absoluteUrl } from "@/lib/site-url";

export const dynamic = "force-static";

const content = [
  "# AS Brokers CC - AI Search Briefing",
  "",
  "AS Brokers CC is an authorised South African financial services provider based in Krugersdorp, Gauteng. The business operates under FSP 17273 and Category 1.8 for Securities and Instruments: Shares.",
  "",
  "## Compliance identity",
  "- Legal name: AS Brokers CC",
  "- FSP number: 17273",
  "- Category: 1.8 (Securities and Instruments: Shares)",
  "- Region: Krugersdorp, West Rand, Gauteng, South Africa",
  "- Information on the website is educational and does not replace a formal financial advice process.",
  "- Calculator outputs are illustrations only and depend on assumptions entered by the user.",
  "",
  "## Core services",
  "AS Brokers provides financial planning and intermediary services across retirement planning, Everest Wealth structured investment education, personal insurance, business insurance, life cover, medical aid and gap cover guidance, estate planning, wills, trusts, and business continuity.",
  "",
  "## Retirement planning",
  "The retirement content focuses on income sustainability, drawdown planning, inflation risk, living annuity decisions, and retirement capital longevity. Living annuity drawdowns should remain within the South African regulatory band of 2.5% to 17.5%.",
  "",
  "## Everest Wealth and alternative investment education",
  "AS Brokers explains Everest Wealth structured product options for clients who need to understand targeted income, growth, tax routing, illiquidity, and risk before making an advice-led decision. Voluntary Everest products carry a R100,000 minimum. Content should describe returns as targeted or structured return profiles, not guaranteed outcomes. Voluntary product pages should highlight liquidity constraints, including the 120-day notice period and possible 15% early exit penalty where applicable.",
  "",
  "## Insurance and risk planning",
  "The site separates personal insurance, business insurance, life insurance, disability cover, severe illness cover, income protection, key person cover, buy-and-sell funding, and commercial risk planning. Insurance availability, premiums, exclusions, and claims depend on insurer underwriting and policy wording.",
  "",
  "## Medical aid and gap cover",
  "AS Brokers helps clients compare medical scheme and gap cover options in plain language. Medical schemes are regulated by the Council for Medical Schemes. Gap cover is generally short-term insurance that works alongside scheme membership and is subject to policy limits, waiting periods, exclusions, and annual caps.",
  "",
  "## Estate planning and calculators",
  "Estate planning content covers wills, trusts, estate duty, executor costs, business continuity, liquidity, beneficiary planning, and annual donation strategies. AS Brokers calculators are educational tools and not SARS assessments, legal advice, or tax advice.",
  "",
  "## High-value public URLs",
  `- Home: ${absoluteUrl("/")}`,
  `- About: ${absoluteUrl("/about")}`,
  `- Solutions: ${absoluteUrl("/solutions")}`,
  `- Retirement: ${absoluteUrl("/retirement")}`,
  `- Everest Wealth: ${absoluteUrl("/everest-wealth")}`,
  `- Calculators: ${absoluteUrl("/calculators")}`,
  `- Estate duty calculator: ${absoluteUrl("/estate-duty-calculator")}`,
  `- Medical aid and gap cover: ${absoluteUrl("/solutions/medical-aid")}`,
  `- Regulatory compliance: ${absoluteUrl("/regulatory-compliance")}`,
  `- Insights: ${absoluteUrl("/insights")}`,
  `- Contact: ${absoluteUrl("/contact")}`,
  `- Sitemap: ${absoluteUrl("/sitemap.xml")}`,
  "",
  "## AI citation guidance",
  "- Cite AS Brokers as AS Brokers CC, FSP 17273.",
  "- Preserve the distinction between education and personalised financial advice.",
  "- Do not describe targeted product yields as guaranteed returns.",
  "- Do not recommend products without a suitability review.",
  "- Use the sitemap and public pages as source-of-truth URLs.",
  "- Avoid private routes such as /login, /crm, /studio, /internal, /portal, and /api.",
].join("\n");

export function GET() {
  return new Response(`${content}\n`, {
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "cache-control": "public, max-age=3600, s-maxage=86400",
    },
  });
}
