import sanitizeHtml from "sanitize-html";

/**
 * Strips scripts/event handlers while keeping typical article HTML.
 * Applied when saving a published version; public pages use stored output.
 */
export function sanitizeInsightBody(html: string): string {
  return sanitizeHtml(html, {
    allowedTags: sanitizeHtml.defaults.allowedTags.concat([
      "section",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "img",
      "figure",
      "figcaption",
      "hr",
      "table",
      "thead",
      "tbody",
      "tfoot",
      "tr",
      "th",
      "td",
      "colgroup",
      "col",
      "iframe",
      "script",
      "form",
      "label",
      "input",
      "textarea",
      "button",
      "select",
      "option",
    ]),
    allowedAttributes: {
      ...sanitizeHtml.defaults.allowedAttributes,
      "*": ["class", "style", "id"],
      img: ["src", "srcset", "alt", "title", "width", "height", "loading", "class"],
      table: ["class"],
      th: ["colspan", "rowspan", "class"],
      td: ["colspan", "rowspan", "class"],
      a: ["href", "name", "target", "rel", "class"],
      iframe: [
        "src",
        "title",
        "width",
        "height",
        "allow",
        "allowfullscreen",
        "loading",
        "referrerpolicy",
        "frameborder",
      ],
      script: ["src", "type", "async", "defer", "crossorigin", "integrity", "referrerpolicy", "id", "class"],
      form: ["action", "method", "class", "id", "name", "autocomplete", "novalidate"],
      label: ["for", "class", "id"],
      input: [
        "type",
        "id",
        "name",
        "value",
        "min",
        "max",
        "step",
        "placeholder",
        "required",
        "readonly",
        "disabled",
        "checked",
        "autocomplete",
        "inputmode",
        "class",
        "style",
      ],
      textarea: ["id", "name", "rows", "cols", "placeholder", "required", "readonly", "disabled", "class", "style"],
      button: ["type", "disabled", "class", "style"],
      select: ["id", "name", "required", "disabled", "class", "style"],
      option: ["value", "selected", "disabled", "class", "style"],
    },
    allowedSchemes: ["http", "https", "mailto", "tel"],
    allowProtocolRelative: false,
    allowVulnerableTags: true,
    allowedIframeHostnames: ["www.youtube.com", "youtube.com", "www.youtube-nocookie.com", "player.vimeo.com"],
  });
}
